### ISSUE TITLE
Setting up realsense on ROS2 humble

### ISSUE THREAD

**Issue by Swithinraj** [HBRS-SDP/ws23-solo12#2]
Setting up Realsense camera module for simulation on ROS2 Humble for further developments and testing.

**Comment by harleylara** [comment]
Is this related with the Software Development Project for the Solo 12 robot ?

**Comment by Swithinraj** [comment]
No sorry it was a mistake on my part. I did it on the wrong work space. I
corrected it. It is supposed to be for project following robot.
